import jsPDF from "jspdf";

export const generateCropReport = (result) => {
  const doc = new jsPDF();

  // HEADER
  doc.setFontSize(24);

  doc.text("AgriSync AI Report", 20, 25);

  // LINE
  doc.line(20, 32, 190, 32);

  // CONTENT
  doc.setFontSize(16);

  doc.text(
    `Recommended Crop: ${result.recommended_crop}`,
    20,
    55
  );

  doc.text(
    `AI Confidence: ${result.confidence}`,
    20,
    75
  );

  doc.text(
    `Estimated Profit: ${result.estimated_profit}`,
    20,
    95
  );

  // INSIGHTS
  doc.setFontSize(18);

  doc.text("AI Insights", 20, 125);

  doc.setFontSize(14);

  doc.text(
    "• Soil conditions are favorable for cultivation.",
    25,
    145
  );

  doc.text(
    "• Climate and rainfall are suitable for this crop.",
    25,
    160
  );

  doc.text(
    "• Maintain proper nitrogen balance for higher yield.",
    25,
    175
  );

  // FOOTER
  doc.setFontSize(12);

  doc.text(
    "Generated by AgriSync AI",
    20,
    270
  );

  // SAVE PDF
  doc.save("AgriSync_AI_Report.pdf");
};